type:	seq
sequence:
	-	type:	map
		mapping:
			"name":
				required:	true
				unique: yes
				type:	str
			"format":
				required:	true
				type:	seq
				sequence:
					-	type:	map
						mapping:
							"label":
								type:	str
							"type":
								required:	true
								enum:
									-	UINT8
									-	SINT8
									-	BIT8
									-	OCT8
									-	HEX8
									-	DUMMY8
									-	UINT16
									-	SINT16
									-	BIT16
									-	OCT16
									-	HEX16
									-	DUMMY16
									-	UINT32
									-	SINT32
									-	BIT32
									-	OCT32
									-	HEX32
									-	DUMMY32
